### ISSUE TITLE
Experhash-0.1.1/priv/experhash_port: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by jpinnix** [kemonomachi/experhash#11]
Experhash is working fine locally, but in production I am getting an error. I'm using Distillery 2 and Docker to make releases on Ubuntu 16.04. Imagemagick is installed on both the docker image and on the production server, and `mix compile` runs during the build.

Genserver times out, but I believe that is just a symptom.

`experhash-0.1.1/priv/experhash_port: Syntax error: word unexpected (expecting ")")`

Phoenix 1.4.3
Elixir 1.8.1
Distillery 2.0 using the new Elixir provider

```elixir
11:07:51.097 request_id=FZXvw-ylKvX9vlEAAADx [debug] Processing with DistanceWeb.DocumentController.new/2
  Parameters: %{}
  Pipelines: [:browser]
11:07:51.098 request_id=FZXvw-ylKvX9vlEAAADx [info] Sent 200 in 3ms
11:08:02.951 request_id=FZXvxq9fFd2k4d0AAAEB [info] POST /documents
11:08:02.955 request_id=FZXvxq9fFd2k4d0AAAEB [debug] Processing with DistanceWeb.DocumentController.create/2
  Parameters: %{"_csrf_token" => "RysAfnR6Yk4BenoDIB0KAgxlDDU8JgAA3n//DH7xH77LcEr0EP8EVQ==", "_utf8" => "✓", "document" => %{"file" => %Plug.Upload{content_type: "image/png", filename: "a028.png", path: "/tmp/plug-1555/multipart-1555412882-15036320304116-1"}}}
  Pipelines: [:browser]
/home/deploy/lib/experhash-0.1.1/priv/experhash_port: 1: /home/deploy/lib/experhash-0.1.1/priv/experhash_port: Syntax error: word unexpected (expecting ")")
11:08:12.959 request_id=FZXvxq9fFd2k4d0AAAEB [info] Converted exit {:timeout, {GenServer, :call, [#PID<0.1680.0>, {:command, {:hash, :dd, "media/1555412882-15036320304116-1-a028-orig.png", 8}}, 10000]}} to 500 response
11:08:12.961 request_id=FZXvxq9fFd2k4d0AAAEB [error] Process #PID<0.1678.0> terminating
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: {{:timeout, {GenServer, :call, [#PID<0.1680.0>, {:command, {:hash, :dd, "media/1555412882-15036320304116-1-a028-orig.png", 8}}, 10000]}}, {DistanceWeb.Endpoint, :call, [%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: [], body_params: %Plug.Conn.Unfetched{aspect: :body_params}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "redacted", method: "POST", owner: #PID<0.1678.0>, params: %Plug.Conn.Unfetched{aspect: :params}, path_info: ["documents"], path_params: %{}, port: 80, private: %{}, query_params: %Plug.Conn.Unfetched{aspect: :query_params}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.5"}, {"connection", "upgrade"}, {"content-length", "30026"}, {"content-type", "multipart/form-data; boundary=---------------------------7719490031198181894888934539"}, {"cookie", "_distance_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYdEUvUTAyVTZJTU1PQ1h4Mkk1NHBqdz09.Ojpdcrhb9AN8xoU4Sjxl5rR-uCsb6wFd-FJlt6vuz4Y"}, {"host", "redacted"}, {"referer", "https://redacted/documents/new"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0"}, {"x-cluster-client-ip", "97.89.62.78"}, {"x-forwarded-for", "97.89.62.78"}], request_path: "/documents", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}], scheme: :http, script_name: [], secret_key_base: nil, state: :unset, status: nil}, []]}}
(phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:49: Phoenix.Endpoint.Cowboy2Handler.init/2
(cowboy) /redacted/distance/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
```

**Comment by kemonomachi** [comment]
Interesting!

Something makes the system not recognize that `experhash_port` is an executable. Instead, it tries to run it as a shell script, which of course fails spectacularly.

I did some googling and found this thread on the Elixir Forum: https://elixirforum.com/t/experhash-0-1-1-priv-experhash-port-syntax-error-word-unexpected-expecting/21666. I'm guessing you are the same jpinnix, so it looks like you found a workaround at least. Sounds like the Makefile is wonky, which is not surprising considering I don't really know make. I'll take a look at it when I have some spare time.

(Sorry for the late answer, I've been away on vacation. And yes, I'm not actively working on this project, but I do want to fix any errors people find.)

**Comment by jpinnix** [comment]
I don't know make either, haha.

Let me know if I can help. And no worries about the delay. I hope you had a restful vacation!

**Comment by kemonomachi** [comment]
Good news: I found out that there is a ready-made make compile task for mix now: https://github.com/elixir-lang/elixir_make. With the environment variables it adds, it'll make it easier to put build output where it belongs. (It is also more polished than my custom task)

**Comment by jpinnix** [comment]
Nice!

**Comment by jpinnix** [comment]
Nice!

**Comment by kemonomachi** [comment]
Have switched over to elixir_make now, will figure out the rest on Wednesday

**Comment by kemonomachi** [comment]
@jpinnix I've shuffled things around a bit now. Could you try the latest master, to see if it works for you? I didn't leave any cleanup for the old location, so please run `mix deps.clean experhash` before updating.

I'm now placing all C++ output in the _build folder instead, in the proper location for whatever mix environment is set.

**Comment by jpinnix** [comment]
Absolutely. I’ll give it a whir. Thanks!

**Comment by jpinnix** [comment]
@kemonomachi This works perfectly! Thank you so much!
